"""
Each new term in the Fibonacci sequence is generated by adding the previous
two terms. By starting with 1 and 2, the first 10 terms will be:
 
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 
By considering the terms in the Fibonacci sequence whose values do not
exceed four million, find the sum of the even-valued terms.
"""

import time

start = time.time()

n = 4000000
fibSequence = [1, 2]
x = 1
evens = [2]

while (x < 4000000):
    fibSequence.append(fibSequence[-1] + fibSequence[-2])
    x = fibSequence[-1]
    if (x % 2 == 0):
        evens.append(x)

print 'Answer: ' + str(sum(evens))
print 'Time:   ' + '{:0.2f}'.format(time.time()-start) + 's'